### ISSUE TITLE
Container for all the TODO stuff

### ISSUE THREAD

**Issue by jeskko** [jeskko/huntbot#3]
- [x] Split the code in multiple files to make it more manageable
- [x] Add an undo feature
- [x] Lose the Google sheets "database" and store the data in local db
  - [ ] Add a web-based management tool for hunt status database
- [ ] see if aiosqlite is easily implementable
- [ ] ways to interact with issued webhook messages: undo shout / cancel, mark as ended? (can be complicated)
- [x] unify legacy parameter handling in commands, make it understand 2-6 in addition to l everywhere.
